# Generated by Django 5.2 on 2025-04-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_add_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_visit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
