# Generated by Django 5.2 on 2025-04-26 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_ready_to_discharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='isi_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
