# Generated by Django 5.2 on 2025-04-26 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_isi_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISIScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isi_scores', to='patients.patient')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['patient', 'date'], name='patients_is_patient_8194c5_idx')],
            },
        ),
    ]
