# Generated by Django 5.2 on 2025-04-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_isiscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isiscore',
            name='notes',
        ),
    ]
