# Generated by Django 5.2 on 2025-04-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_remove_isiscore_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isiscore',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='isiscore',
            name='updated_at',
        ),
    ]
