# Generated by Django 5.2 on 2025-04-26 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_remove_isiscore_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='isi_score',
        ),
    ]
