# Generated by Django 5.2 on 2025-04-27 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_remove_patient_isi_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
    ]
