# Generated by Django 5.2 on 2025-04-27 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_update_extra_data_default'),
        ('patients', '0010_remove_address_country'),
    ]

    operations = [
    ]
