# Generated by Django 5.2 on 2025-04-27 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_merge_20250427_0410'),
        ('patients', '0011_rename_extra_data_to_additional_fields'),
    ]

    operations = [
    ]
