# Generated by Django 5.2 on 2025-04-27 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_merge_20250427_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='additional_fields',
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_visit',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('inquiry', 'Inquiry'), ('onboarding', 'Onboarding'), ('active', 'Active'), ('churned', 'Churned')], db_index=True, default='inquiry', max_length=10),
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True)),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='patients.customfield')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='patients.patient')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('patient', 'field_definition'), name='unique_patient_custom_field')],
            },
        ),
    ]
